language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install: npm install
before_script: npm run dist
script: npm test
before_deploy: "echo 'All unit tests passed; Successfully built distribution assets; Preparing to deploy Homepage App to AWS'"
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $AWS_PRODUCTION_ACCESS_KEY_ID
  secret_access_key: "$AWS_PRODUCTION_ACCESS_SECRET"
  region: us-east-1
  app: $AWS_APP_NAME
  env: $AWS_ENVIRONMENT_NAME
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: $AWS_APP_NAME
  on:
    repo: NYPL/dgx-homepage
    branch: master
after_deploy: "echo 'Successfully executed deploy trigger for Homepage App on AWS'"
