branch-defaults:
  aws-eb:
    environment: nypl-homepage-dev
    group_suffix: null
  development:
    environment: nypl-homepage-dev
    group_suffix: null
  master:
    environment: nypl-homepage-production
    group_suffix: null
global:
  application_name: nypl-homepage-app
  branch: null
  default_ec2_keyname: dgdvteam
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
